### ISSUE TITLE
Build app

### ISSUE THREAD

**Issue by 98saiful** [gnovakov/PopularMovies_Kotlin#2]
![image](https://user-images.githubusercontent.com/8509342/110203654-51fce380-7eaa-11eb-8300-10f8f5aec250.png)
Hi there, got error building the project. How to solve it?

**Comment by gnovakov** [comment]
You need to sign up for a https://www.themoviedb.org/ API key and replace it with where it says MovieDbAPIKey, best place is to store it in your BuildConfig on your computer, you can find tutorials online how to do this.

The reason to do this is to hide your API Key so other people don't use it, so they have to get their own.
